server:
  port: 8082
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
spring:
  sentinel:
    transport:
      dashboard: localhost:8090
    http-method-specify: true
feign:
  okhttp:
    enabled: true
  main:
    allow-circular-references: true
  sentinel:
    enabled: true
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
  swagger:
    title: 用户服务接口文档
    package: com.hmall.user.controller
  db:
    database: hm-user
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123